apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mon-hpa-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mon-super-site
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50